---
title: "MP 2"
author: "Zoya Alam and  Khulood Fahim"
date: "3/20/2019"
output: 
  html_document:
    code_folding: hide
---

```{r}
library(tidyverse)
library(naniar)
library(extrafont)
library(xkcd)
library("ggthemes")
library(ggrepel)
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```

## Part 1 : California 
```{r}
committees <- committees %>%
  select(cmte_id, cmte_name, cmte_state, cand_id) 
committees

# selected desired information from committees dataset

candidates <- candidates %>%
  select(cand_id, cand_name, cand_party_affiliation, cand_office, cand_state)
candidates

#selected desired information from candidates dataset

contributions <- contributions %>%
  select(cmte_id, name, state, cand_id, transaction_amt, transaction_type) %>%
  filter(!transaction_type == "24A")
contributions

# selected desired information from contributions dataset and filtered out contributions made against candidates

new_house <- house_elections %>%
  select(fec_id, state,  incumbent, party, primary_votes) %>%
  rename(cand_id= "fec_id")
new_house 

# edited house_elections table to select information and rename a variable to make joining possible 

joined_dataset <- inner_join(committees, candidates, by= "cand_id")
joined_dataset

# joined committees and candidates datasets

j2_dataset <- inner_join(new_house, joined_dataset, by= "cand_id")
j2_dataset

# joiened new_house and joined_dataset to add new_house information to the merged candidates and committees dataset

j3_dataset <- inner_join(j2_dataset, contributions, by= "cand_id") 
j3_dataset

# added contributions dataset to latest table, merging all four datasets together 

j3_dataset_total <- j3_dataset %>%
 select(cand_id, state.x, incumbent, party, cmte_id.x, cmte_name, cand_party_affiliation, cand_office, state.y, transaction_amt) %>%
  group_by(cand_id) %>% 
summarize(total_contributions= sum(transaction_amt))
j3_dataset_total

# calculated total contributions made per candidate 

j3_dataset_state <- j3_dataset %>%
  select(state.x, cand_id, transaction_amt) %>%
  group_by(state.x) %>%
  mutate(state_contribution = sum(transaction_amt)) 
j3_dataset_state

# calculated total contributions made to all candidates in a state

j3_dataset_final <- inner_join(j3_dataset_total, j3_dataset_state, by= "cand_id") %>%
select(-transaction_amt) %>%
  group_by(cand_id) %>%
  mutate(percentage_contrib= (total_contributions/state_contribution)*100) %>%
  summarize(meanpc = mean(percentage_contrib))
j3_dataset_final

# merged information of total and state contributions to calculate for percentage of contributions recieved by each candidate in a state (mean(total_contributions/state.contribution)*100))

j3_finaldataset <- inner_join(j3_dataset_total, j3_dataset_final, by=  "cand_id")
j3_finaldataset

# joined datasets to include total contributions, which is needed for y-axis of plot 

final_dataset <- inner_join(j2_dataset, j3_dataset_final, by= "cand_id") %>%
  select(cand_id, state, incumbent, party, cand_office, meanpc, cmte_id) 
final_dataset

# created a dataset with information to be used in calculating number of committees contributing to each candidate 

final_dataset2  <- final_dataset %>%
  select(cand_id, state, incumbent, party, cmte_id, cand_office, meanpc) %>%
  group_by(cand_id) %>%
 summarize(number_com=  n_distinct(cmte_id))
final_dataset2

# calculated number of committees contributing to each candidate 

parties <- c("D", "R")
final_dataset_new <- final_dataset2 %>%
  inner_join(j3_finaldataset, by = "cand_id")%>%
  inner_join(new_house, by = "cand_id") %>%
  filter(party %in% parties) %>%
  mutate(log_tc= log(total_contributions))
final_dataset_new

# filtered for needed political parties, combined three datasets to join all information needed for visualization. Also created a log of total contributions to spread out y-axis in visualization. 
```

```{r}
state_function <- function(state_name) {
  final_dataset_new %>% 
  filter(state == state_name)
}

# created a function to enable us to apply code to different states

cali_set <- state_function(state_name = "CA")

# applied the function and filtered for California as an initial example
```

```{r}
set.seed(76)
cali_set %>%
  ggplot(aes(x = primary_votes, y = log_tc, color = incumbent, size = number_com)) +
  geom_point(alpha = 0.5) +
  geom_jitter() +
  labs(x= "Number of Primary Votes", 
       y= "Total Contributions (log)", 
       size= "Number of Committees", 
       color= "Incumbent Status", 
       title = "Votes and Contributions by Incumbent Status") + theme_minimal()+
  scale_color_manual(values = c("TRUE" = "#B833FF", "FALSE" = "#77FF33")) +
  theme (axis.title.y = element_text(family = "Century Gothic", size = 15), 
        axis.title.x = element_text(family = "Century Gothic", size = 15),
        axis.text.y = element_text(family = "Century Gothic", size = 8), 
        axis.text.x = element_text(family = "Century Gothic", size = 8),
        plot.title = element_text(family = "Century Gothic", size = 18),
        legend.title = element_text(family = "Century Gothic", size = 15),
        legend.text = element_text(family = "Century Gothic", size = 8))

# created a scatter plot showing the relationship between the number of primary votes and total contributions for each candidate, in addition to factoring in number of committees contributing to each candidate (mapped to size) and whether or not candidate was an incumbent (mapped to color)

set.seed(76)
cali_set %>%
  ggplot(aes(x = primary_votes, y = log_tc, color = party, size = number_com)) +
  geom_point() +
  geom_jitter() +
  labs(x= "Number of Primary Votes", 
       y= "Total Contributions (log)", 
       color= "Party Type", 
       size= "Number of Committees", 
       title = "Votes and Contributions by Party") + theme_minimal() +
  scale_color_manual(values = c("D" = "#04417A", "R" = "#E22E2F")) +
  theme (axis.title.y = element_text(family = "Century Gothic", size = 15), 
        axis.title.x = element_text(family = "Century Gothic", size = 15),
        axis.text.y = element_text(family = "Century Gothic", size = 8), 
        axis.text.x = element_text(family = "Century Gothic", size = 8),
        plot.title = element_text(family = "Century Gothic", size = 18),
        legend.title = element_text(family = "Century Gothic", size = 15),
        legend.text = element_text(family = "Century Gothic", size = 8))

# created a scatter plot showing the relationship between the number of primary votes and total contributions for each candidate, in addition to factoring in number of committees contributing to each candidate (mapped to size) and the part affiliation of each candidate (mapped to color)
```

## Part 2: Top Ten States

```{r}
top_calc <- final_dataset_new %>%
  group_by(state) %>%
  summarise(meanpc)
  glimpse(top_calc) %>%
  arrange(meanpc) %>%
  head(10)
top_calc

```


```{r}
top_state <- c("CA", "TX", "FL", "NY", "PA", "NC", "NJ", "GA", "AZ", "MA")
```


```{r}
final_dataset_new %>% 
  filter(state %in% top_state) %>%
  ggplot(aes(x = primary_votes, y = log_tc, color = incumbent, size = number_com)) +
  geom_point(alpha = 0.5) +
  geom_jitter() +
  labs(x= "Number of Primary Votes", 
       y= "Total Contributions (log)", 
       size= "Number of Committees", 
       color= "Incumbent Status", 
       title = "Votes and Contributions by Incumbent Status") + theme_minimal()+
  scale_color_manual(values = c("TRUE" = "#B833FF", "FALSE" = "#77FF33")) +
  theme (axis.title.y = element_text(family = "Century Gothic", size = 15), 
        axis.title.x = element_text(family = "Century Gothic", size = 15),
        axis.text.y = element_text(family = "Century Gothic", size = 8), 
        axis.text.x = element_text(family = "Century Gothic", size = 8),
        plot.title = element_text(family = "Century Gothic", size = 18),
        legend.title = element_text(family = "Century Gothic", size = 15),
        legend.text = element_text(family = "Century Gothic", size = 8)) +
  facet_wrap(~as.factor(state), scales = "free_x")
```

```{r}
final_dataset_new %>%
  filter(state %in% top_state) %>%
  ggplot(aes(x = primary_votes, y = log_tc, color = party, size = number_com)) +
  geom_point() +
  geom_jitter() +
  labs(x= "Number of Primary Votes", 
       y= "Total Contributions (log)", 
       color= "Party Type", 
       size= "Number of Committees", 
       title = "Votes and Contributions by Party") + theme_minimal() +
  scale_color_manual(values = c("D" = "#04417A", "R" = "#E22E2F")) +
  theme (axis.title.y = element_text(family = "Century Gothic", size = 15), 
        axis.title.x = element_text(family = "Century Gothic", size = 15),
        axis.text.y = element_text(family = "Century Gothic", size = 8), 
        axis.text.x = element_text(family = "Century Gothic", size = 8),
        plot.title = element_text(family = "Century Gothic", size = 18),
        legend.title = element_text(family = "Century Gothic", size = 15),
        legend.text = element_text(family = "Century Gothic", size = 8)) +
  facet_wrap(~as.factor(state), scales = "free_x")
```

```{r}
top_votes <- final_dataset_new %>%
  inner_join(top_state, by = "state") 
top_votes

top_state <- top_votes %>%
  group_by(state) %>%
  summarise(max = max(primary_votes))
  
top_cand <- top_votes %>%
  group_by(cand_id) %>%
  summarise(max = max(primary_votes))

top_table <- top_cand %>%
  inner_join(top_state, by = "max") 

top_name <- top_table %>%
  inner_join(candidates, by = "cand_id") %>%
  select(-cand_party_affiliation, -cand_office) %>%
  inner_join(final_dataset_new, by = "cand_id")
top_name
```
